// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzROGotVz7YkD5-ObZZfQ20mPUTb9SzC8',
    appId: '1:822035904494:web:4b41313b5fad2944ac40ff',
    messagingSenderId: '822035904494',
    projectId: 'konversisuhu-8a72e',
    authDomain: 'konversisuhu-8a72e.firebaseapp.com',
    storageBucket: 'konversisuhu-8a72e.firebasestorage.app',
    measurementId: 'G-S1VC5JY8PV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeORwyPRf2t3k22LQSvQn70yoHga_1s1U',
    appId: '1:822035904494:android:059257757f901a6bac40ff',
    messagingSenderId: '822035904494',
    projectId: 'konversisuhu-8a72e',
    storageBucket: 'konversisuhu-8a72e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcrUb4CBWwqCmtVHTnhvv6kwY_6KNq_do',
    appId: '1:822035904494:ios:e869dfdaa5f5dfffac40ff',
    messagingSenderId: '822035904494',
    projectId: 'konversisuhu-8a72e',
    storageBucket: 'konversisuhu-8a72e.firebasestorage.app',
    iosBundleId: 'com.example.konfSuhuProvider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcrUb4CBWwqCmtVHTnhvv6kwY_6KNq_do',
    appId: '1:822035904494:ios:e869dfdaa5f5dfffac40ff',
    messagingSenderId: '822035904494',
    projectId: 'konversisuhu-8a72e',
    storageBucket: 'konversisuhu-8a72e.firebasestorage.app',
    iosBundleId: 'com.example.konfSuhuProvider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzROGotVz7YkD5-ObZZfQ20mPUTb9SzC8',
    appId: '1:822035904494:web:5e91afad1e124ac8ac40ff',
    messagingSenderId: '822035904494',
    projectId: 'konversisuhu-8a72e',
    authDomain: 'konversisuhu-8a72e.firebaseapp.com',
    storageBucket: 'konversisuhu-8a72e.firebasestorage.app',
    measurementId: 'G-9ZQD4M3Y96',
  );
}
